export const CLIENT_DATA = [
    { client: 'Assai Paralela', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Rmix Alphaville', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Assai Pau Da Lima', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Rmix Imbui', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Gbarbosa Cd Bahia', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Cdp Armacao Stiep Loja 14', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Assai Vasco Da Gama', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Redemix Rio Vermelho', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Pitubinha', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Amazonas', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Masani', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Buraquinho', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Stella Maris', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Atakarejo Lauro de Freitas', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Trielo Ceasa BA', vendedor: 'Filial', rede: 'Trielo', uf: 'BA' },
    { client: 'Cdp Rodoviaria Loja 17', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Rmix Ondina', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Vitoria', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Horto', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Assai Calcada', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Cdp Sete Portas Loja 09', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Deli E Cia Graca', vendedor: 'Ricardo Santos', rede: 'Deli E Cia', uf: 'BA' },
    { client: 'Cdp Catu Loja 12', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Cdp Super Centro Mata Loja 10', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Alagoinhas Loja 11', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Centro Dias Davila', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Centro - Mata S.J. Sede', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Mateus Juazeiro', vendedor: 'Antonio', rede: 'Mateus Lojas', uf: 'BA' },
    { client: 'Assai Sr Do Bonfim', vendedor: 'Antonio', rede: 'Assai', uf: 'BA' },
    { client: 'Rf Supermercado Brasil', vendedor: 'Antonio', rede: 'Outros', uf: 'BA' },
    { client: 'Frutos Da Terra', vendedor: 'Antonio', rede: 'Outros', uf: 'PE' },
    { client: 'Feirao Das Frutas Atras Banca', vendedor: 'Antonio', rede: 'Feirao Das Frutas', uf: 'PE' },
    { client: 'Feirao Das Frutas Maria Auxiliadora', vendedor: 'Antonio', rede: 'Feirao Das Frutas', uf: 'PE' },
    { client: 'Assai Juazeiro', vendedor: 'Antonio', rede: 'Assai', uf: 'BA' },
    { client: 'Bontempo Supermercados', vendedor: 'Antonio', rede: 'Outros', uf: 'PE' },
    { client: 'Flor Da Chapada Itaberaba', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Sams Aracaju', vendedor: 'Vinicius', rede: 'Sams', uf: 'SE' },
    { client: 'G. Barbosa Francisco Porto', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'Gbarbosa Hiper Sul', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'G. Barbosa - Rio Mar', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'Supermercado Bombom Aracaju', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Atakarejo Patamares', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Rmix Ponto Verde Vila Laura', vendedor: 'Vinicius', rede: 'Ponto Verde', uf: 'BA' },
    { client: 'Sams Pituba', vendedor: 'Vinicius', rede: 'Sams', uf: 'BA' },
    { client: 'Assai Cabula', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Sams Bonoco', vendedor: 'Vinicius', rede: 'Sams', uf: 'BA' },
    { client: 'Assai Paripe', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Sams Lauro De Freitas', vendedor: 'Vinicius', rede: 'Sams', uf: 'BA' },
    { client: 'Assai Camacari', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Atakarejo Cd Simoes Filho', vendedor: 'Ricardo Santos', rede: 'Atakarejo Cds', uf: 'BA' },
    { client: 'Hiperideal Piata Orlando Gomes', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Patamares Lj23', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Piata Otavio Mangabeira', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Horto', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Atakarejo Vasco da Gama', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Hiperideal Jardins (Juracy Acm)', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Buraquinho', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Assai Barris', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Hiperideal Caminho Das Arvores', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Manoel Dias Pituba', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Itaigara', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Atacadão Camaçari', vendedor: 'Nixon', rede: 'Atacadao', uf: 'BA' },
    { client: 'Perini Pituba', vendedor: 'Vinicius', rede: 'Perini', uf: 'BA' },
    { client: 'Hiperideal Pituba Rua Ceara', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Barra', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Canela', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal - Vitoria', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Perini Graca', vendedor: 'Vinicius', rede: 'Perini', uf: 'BA' },
    { client: 'Redemix Chame-Chame', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Hiperideal Guarajuba', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Atakarejo Itacimirim', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Hiperideal Feira De Santana', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Atakarejo Feira De Santana', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Sams Feira De Santana', vendedor: 'Vinicius', rede: 'Sams', uf: 'BA' },
    { client: 'Atakarejo Ilheus', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Atakarejo Aracaju', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'SE' },
    { client: 'Mateus Jose Conrado Aracaju', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'SE' },
    { client: 'Mateus Santa Monica', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'SE' },
    { client: 'Assai Petrolina', vendedor: 'Antonio', rede: 'Assai', uf: 'PE' },
    { client: 'Mateus Cd - Feira De Santana', vendedor: 'Ricardo Santos', rede: 'Mateus Cds', uf: 'BA' },
    { client: 'Economart Feira De Santana', vendedor: 'Ricardo Santos', rede: 'Economart', uf: 'BA' },
    { client: 'Paris Delicatessen', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Atakarejo Boca Do Rio', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Hiperideal Praia Do Forte', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Parque Shopping', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Gbarbosa Jardins', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'G Barbosa Farolandia', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'Hiper Carnes Barra Dos Coqueiros', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'HiperCarnes Jabotiana Aracaju', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Gran Hortifruti Pituba', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Assai Rotula', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'A. Cecilio Mota Jacobina', vendedor: 'Antonio', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Pga Juazeiro', vendedor: 'Antonio', rede: 'Outros', uf: 'BA' },
    { client: 'Gbarbosa 035 Costa Azul', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gbarbosa-302 - Horto Bela Vista', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Supermercado Jhones Itaberaba', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Supermercado Jl Itaberaba', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Gbarbosa 108 Lauro De Freitas', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Atakarejo Ilha Itaparica', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Gbarbosa-274-Guarajuba', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Hiperideal Orla', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Armacao', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Gbarbosa 037 Alagoinhas', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gbarbosa 015 Feira De Santana', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Hiperideal Stella Maris II', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Gbarbosa Luzia', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'Gbarbosa Sao Cristovao', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'Atakarejo Cd Vitoria Da Conquista', vendedor: 'Ricardo Santos', rede: 'Atakarejo Cds', uf: 'BA' },
    { client: 'Hiperideal Vila Laura', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Gbarbosa 029 Brotas', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Mercado Mel Aracaju', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Atakarejo Porto Seguro', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Atakarejo Vit Conquista', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Hiperideal Stella Maris I', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Gral Paniville Pituba', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Assai Mussurunga', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Gbarbosa 074 Sobradinho', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Hiperideal Jardim Apipema', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Hiperideal Patamares Lj13', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Atakarejo Alagoinhas', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Cdp Cd Monte Libano Mata S.J.', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Mercadinho Economico Petrolina', vendedor: 'Antonio', rede: 'Super Economico', uf: 'PE' },
    { client: 'Hiper Ideal Cd', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Roselly Ferreira', vendedor: 'Vinicius', rede: 'Outros', uf: 'BA' },
    { client: 'Gbarbosa Cd Sergipe', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'Massimo Farolandia', vendedor: 'Vinicius', rede: 'Massimo', uf: 'SE' },
    { client: 'Atacadao Petrolina', vendedor: 'Antonio', rede: 'Atacadao', uf: 'PE' },
    { client: 'Economart Vitoria Da Conquista', vendedor: 'Ricardo Santos', rede: 'Economart', uf: 'BA' },
    { client: 'Atakarejo Simoes Filho Lj', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Atakarejo Iguatemi', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Hiperideal Graca', vendedor: 'Ricardo Santos', rede: 'Hiperideal', uf: 'BA' },
    { client: 'Assai Inacio Barbosa', vendedor: 'Nixon', rede: 'Assai', uf: 'SE' },
    { client: 'Perboni Petrolina', vendedor: 'Antonio', rede: 'Outros', uf: 'PE' },
    { client: 'Total Atacado Lauro', vendedor: 'Vinicius', rede: 'Total Atac', uf: 'BA' },
    { client: 'Cdp Boca Do Rio Lj 01', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Marechal', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Unimar Arembepe', vendedor: 'Nixon', rede: 'Outros', uf: 'BA' },
    { client: 'Assai Feira Sobradinho', vendedor: 'Nixon', rede: 'Assai', uf: 'BA' },
    { client: 'Assai N. Sra. Socorro', vendedor: 'Nixon', rede: 'Assai', uf: 'SE' },
    { client: 'Mateus Jacobina', vendedor: 'Antonio', rede: 'Mateus Lojas', uf: 'BA' },
    { client: 'Mateus Itabuna', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'BA' },
    { client: 'Mateus Vitoria Da Conquista', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'BA' },
    { client: 'Mateus Eunapolis', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'BA' },
    { client: 'Mateus Gloria', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'SE' },
    { client: 'Mateus Conceicao Do Coite', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'BA' },
    { client: 'Mateus Porto Seguro', vendedor: 'Ricardo Santos', rede: 'Mateus Lojas', uf: 'BA' },
    { client: 'Atakarejo Pernambues', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Atakarejo Salvador', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Atakarejo Piata', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Atakarejo Baixa De Quintas', vendedor: 'Ricardo Santos', rede: 'Atakarejo Lojas', uf: 'BA' },
    { client: 'Bompreço CD Palmares', vendedor: 'Vinicius', rede: 'Bompreço', uf: 'BA' },
    { client: 'Caravelas Supermercado', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Carballo Alphaville', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Carballo Horto', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Carballo Pituba', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Cbd Costa Azul', vendedor: 'Ricardo Santos', rede: 'Pao de Acucar', uf: 'BA' },
    { client: 'Cdp Alagoinhas I', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Boca Do Rio Loja 07', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Castelo Branco', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Manoel Dia DAvila Loja 04', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Mata S. J. Lj 2', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Mata S. J. Premium', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp Ogunjá', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Cdp São Caetano', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Compre Bem Alagoinhas I', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Compre Bem Alagoinhas II', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Compre Bem Alagoinhas III', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Compre Bem Alagoinhas IV', vendedor: 'Ricardo Santos', rede: 'Cesta Do Povo', uf: 'BA' },
    { client: 'Dist Sao Roque Mangabeira', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Dist Sao Roque Calumbi', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Dist Sao Roque Centro', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Dist Sao Roque Sim', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Dist Sao Roque Sta Monica', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Dist Sao Roque Sto Estevao', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Economart Jequie', vendedor: 'Ricardo Santos', rede: 'Economart', uf: 'BA' },
    { client: 'Economart Luis Eduardo', vendedor: 'Ricardo Santos', rede: 'Economart', uf: 'BA' },
    { client: 'Exito Supermercado Lagarto', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'SE' },
    { client: 'Gb Cabula', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gb CD N. Sra. Do Socorro', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'SE' },
    { client: 'Gb Feira de Santana II', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gb Vit Conquista I', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gb vit Conquista II', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gbarbosa 017 Feira De Santana', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gbarbosa 038 Alagoinhas', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gbarbosa 076 Feira Tomba', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gbarbosa-125-Juazeiro Sa Antonio', vendedor: 'Antonio', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Gbarbosa-133-Juazeiro Centro', vendedor: 'Antonio', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Jn Comercio', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Jns Comercio', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Le Delis Delicatessen', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Massimo - Barra dos Coqueiros', vendedor: 'Vinicius', rede: 'Massimo', uf: 'SE' },
    { client: 'Massimo Luzia', vendedor: 'Vinicius', rede: 'Massimo', uf: 'SE' },
    { client: 'Megga Distribuidora', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Mix Litoral', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'MultiFrios Premium I', vendedor: 'Antonio', rede: 'Outros', uf: 'BA' },
    { client: 'MultiFrios Premium II', vendedor: 'Antonio', rede: 'Outros', uf: 'BA' },
    { client: 'Nunes Peixoto Itabaiana', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Nunes Peixoto N. Sra Gloria', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Perini Vasco', vendedor: 'Vinicius', rede: 'Perini', uf: 'BA' },
    { client: 'Rmix Coageli Lauro', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Cogeali Paripe', vendedor: 'Vinicius', rede: 'Cogeali', uf: 'BA' },
    { client: 'Rmix Itapua', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'Rmix Ponto Verde lapi', vendedor: 'Vinicius', rede: 'Ponto Verde', uf: 'BA' },
    { client: 'Rmix Ponto Verde Sete Portas', vendedor: 'Vinicius', rede: 'Ponto Verde', uf: 'BA' },
    { client: 'Rmix Simoes Filho', vendedor: 'Vinicius', rede: 'Redemix', uf: 'BA' },
    { client: 'SN Soares E Cia', vendedor: 'Ricardo Santos', rede: 'Outros', uf: 'BA' },
    { client: 'Sao Roque Artemia Pires', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Sao Roque Conceicao', vendedor: 'Ricardo Santos', rede: 'Dist Sao Roque', uf: 'BA' },
    { client: 'Super BomBom Estancia', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Trielo CD Simoes Filho BA', vendedor: 'Filial', rede: 'Trielo', uf: 'BA' },
    { client: 'Trielo Paulista PE', vendedor: 'Filial', rede: 'Trielo', uf: 'PE' },
    { client: 'Unimar Barra Pojuca', vendedor: 'Nixon', rede: 'Outros', uf: 'BA' },
    { client: 'Atakarejo Ilheus', vendedor: 'Ricardo', rede: 'Atakarejo', uf: 'BA' },
    { client: 'Atakarejo Porto Seguro', vendedor: 'Ricardo', rede: 'Atakarejo', uf: 'BA' },
    { client: 'Atakarejo Simoes Filho Lj', vendedor: 'Ricardo', rede: 'Atakarejo', uf: 'BA' },
    { client: 'Economart Luis Eduardo', vendedor: 'Ricardo', rede: 'Economart', uf: 'BA' },
    { client: 'Jn Comercio', vendedor: 'Ricardo', rede: 'Outros', uf: 'BA' },
    { client: 'Jns Comercio', vendedor: 'Ricardo', rede: 'Outros', uf: 'BA' },
    { client: 'Le Delis Delicatessen', vendedor: 'Ricardo', rede: 'Outros', uf: 'BA' },
    { client: 'Mateus Eunapolis', vendedor: 'Ricardo', rede: 'Mateus', uf: 'BA' },
    { client: 'Mateus Itabuna', vendedor: 'Ricardo', rede: 'Mateus', uf: 'BA' },
    { client: 'MultiFrios Premium I', vendedor: 'Antonio', rede: 'Outros', uf: 'BA' },
    { client: 'MultiFrios Premium II', vendedor: 'Antonio', rede: 'Outros', uf: 'BA' },
    { client: 'Rf Supermercado Brasil', vendedor: 'Antonio', rede: 'Outros', uf: 'BA' },
    { client: 'SN Soares E Cia', vendedor: 'Ricardo', rede: 'Outros', uf: 'BA' },
    { client: 'Total Atacado Lauro', vendedor: 'Vinicius', rede: 'Mateus', uf: 'BA' },
    { client: 'Unimar Arembepe', vendedor: 'Nixon', rede: 'Outros', uf: 'BA' },
    { client: 'Unimar Barra Pojuca', vendedor: 'Nixon', rede: 'Outros', uf: 'BA' },
    { client: 'Mercadinho Economico Petrolina', vendedor: 'Antonio', rede: 'Outros', uf: 'PE' },
    { client: 'Mercado Mel Aracaju', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Gbarbosa Cd Camaçari', vendedor: 'Vinicius', rede: 'G Barbosa', uf: 'BA' },
    { client: 'Eko Express Aracaju', vendedor: 'Vinicius', rede: 'Outros', uf: 'SE' },
    { client: 'Atakarejo Pojuca', vendedor: 'Ricardo', rede: 'Atakarejo', uf: 'BA' },
    { client: 'Outro (digitar)', vendedor: 'Outro (digitar)', rede: 'Outro (digitar)', uf: 'Outro (digitar)' },
].map(c => ({...c, cliente: c.client}));

export const CLIENT_MAP = new Map(CLIENT_DATA.map(client => [client.client, client]));
export const CLIENTS = [...new Set(CLIENT_DATA.map(item => item.client))].sort();